# Generated by Django 3.2.13 on 2022-05-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pending',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
