# Generated by Django 3.2.13 on 2022-05-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220519_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
